export const MAIL_URL = 'https://gmail.com/'
export const GITHUB_URL = 'https://github.com'
export const LINKEDIN_URL = 'https://www.linkedin.com/in/fadhli-nur-himawan/'
export const FAMOVIE_URL = 'https://fadhyoung.github.io/FAMOVIE/'
export const PORTFOLIO1_URL = 'https://fadhyoung.github.io/Portofolio1/'
export const WHATSAPP_URL = 'https://wa.me/62881026817103'
export const X_URL = 'https://x.com'
